import React from 'react';
import './ItineraryView.css';

/**
 * Helper to process basic markdown bolding (e.g., **text** to <strong>text</strong>)
 */
const renderText = (text) => {
  if (!text) return null;
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part, index) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={index} style={{ color: '#0f172a' }}>{part.slice(2, -2)}</strong>;
    }
    return part;
  });
};

/**
 * Renders the day-by-day itinerary JSON exactly as generated by the AI.
 */
const ItineraryView = ({ itineraryData }) => {
  if (!itineraryData || !itineraryData.days || itineraryData.days.length === 0) {
    return <div className="itinerary-empty">No itinerary available for this trip yet.</div>;
  }

  return (
    <div className="itinerary-container">
      <h3 className="itinerary-main-title">AI-Powered Optimization Plan</h3>
      
      <div className="itinerary-timeline">
        {itineraryData.days.map((dayPlan, idx) => (
          <div key={idx} className="itinerary-day-block">
            <div className="itinerary-day-badge">
              <span>DAY</span>
              <strong>{dayPlan.day}</strong>
            </div>
            
            <div className="itinerary-day-content">
              <h4 className="itinerary-day-title">{dayPlan.title || `Day ${dayPlan.day}`}</h4>
              <p className="itinerary-cost-badge">
                <i className="fa-solid fa-wallet"></i> {dayPlan.estimatedCost || 'Cost varies'}
              </p>

              <div className="itinerary-section">
                <div className="itinerary-time-label">
                  <i className="fa-solid fa-sun" style={{ color: '#fbbf24' }}></i> Morning
                </div>
                <p>{renderText(dayPlan.morning)}</p>
              </div>

              <div className="itinerary-section">
                <div className="itinerary-time-label">
                  <i className="fa-solid fa-cloud-sun" style={{ color: '#f97316' }}></i> Afternoon
                </div>
                <p>{renderText(dayPlan.afternoon)}</p>
              </div>

              <div className="itinerary-section">
                <div className="itinerary-time-label">
                  <i className="fa-solid fa-moon" style={{ color: '#6366f1' }}></i> Evening
                </div>
                <p>{renderText(dayPlan.evening)}</p>
              </div>

              {dayPlan.accommodation && (
                <div className="itinerary-accommodation">
                  <i className="fa-solid fa-bed"></i> <strong>Stay:</strong> {renderText(dayPlan.accommodation)}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ItineraryView;
